export const enum OptionButtonType {
	RECEPIE = 'RECEPIE',
	COOKBOOK = 'COOKBOOK',
	RECEPIE_OWNER = 'RECEPIE_OWNER',
	COOKBOOK_OWNER = 'COOKBOOK_OWNER',
	RECEPIE_SAVED = 'RECEPIE_SAVED',
	COOKBOOK_SAVED = 'COOKBOOK_SAVED',
}
