export enum routePath {
	HOMEPAGE = '/',
	RECEPIES = 'recepies',
	COOKBOOKS = 'cookbooks',
	SIGN_IN = 'signin',
	SIGN_UP = 'signup',
	ABOUT_US = 'aboutus',
	FORGOT_PASSWORD = 'forgotpassword',
	PROFILE = 'profile',
	PROFILE_SETTINGS = 'settings',
	PROFILE_COOKBOOKS = 'cookbooks',
	PROFILE_RECEPIES = 'recepies',
	CREATE = 'create',
	EDIT = 'edit',
}
